export const QUESTIONS = [
  { cat: "Gaming", q: "Welches Spiel hat Creeper?", a: "Minecraft" },
  { cat: "Gaming", q: "Wie heißt Marios Bruder?", a: "Luigi" },
  { cat: "Gaming", q: "Welche Firma entwickelte die PlayStation?", a: "Sony" },
  { cat: "Gaming", q: "Wie heißt Links Prinzessin?", a: "Zelda" },
  { cat: "Gaming", q: "In welchem Spiel gibt es die Map Dust II?", a: "Counter-Strike" },
  { cat: "Gaming", q: "Welches Spiel hat den Battle Royale Modus Warzone?", a: "Call of Duty" },
  { cat: "Gaming", q: "Wie heißt der Hauptcharakter aus God of War?", a: "Kratos" },
  { cat: "Gaming", q: "Welche Farbe hat Sonic meistens?", a: "Blau" },
  { cat: "Gaming", q: "In welchem Spiel gibt es Pikachu?", a: "Pokémon" },
  { cat: "Gaming", q: "Was verliert man in Minecraft beim Tod normalerweise?", a: "Items und XP" },

  { cat: "Anime", q: "Wie heißt Narutos Dämon?", a: "Kurama" },
  { cat: "Anime", q: "Aus welchem Anime ist Ruffy?", a: "One Piece" },
  { cat: "Anime", q: "Wie heißt Light Yagamis Notizbuch?", a: "Death Note" },
  { cat: "Anime", q: "Wie heißt der Bruder von Sasuke?", a: "Itachi" },
  { cat: "Anime", q: "Wie heißt Gokus bekannteste Transformation?", a: "Super Saiyajin" },
  { cat: "Anime", q: "In welchem Anime gibt es Titanen?", a: "Attack on Titan" },
  { cat: "Anime", q: "Wie heißt Dekus richtiger Name?", a: "Izuku Midoriya" },
  { cat: "Anime", q: "Aus welchem Anime ist Tanjiro?", a: "Demon Slayer" },
  { cat: "Anime", q: "Welche Frucht isst Ruffy?", a: "Gum-Gum-Frucht" },
  { cat: "Anime", q: "Wie heißt Kanekis Maske grob?", a: "Ghoul-Maske" },

  { cat: "Filme", q: "Wie heißt der Zauberer mit der Blitznarbe?", a: "Harry Potter" },
  { cat: "Filme", q: "Wie heißt der Bösewicht in Star Wars mit Atemmaske?", a: "Darth Vader" },
  { cat: "Filme", q: "In welchem Film gibt es den Ring der Macht?", a: "Herr der Ringe" },
  { cat: "Filme", q: "Wie heißt der Clown aus Es?", a: "Pennywise" },
  { cat: "Filme", q: "Welcher Superheld ist Bruce Wayne?", a: "Batman" },
  { cat: "Filme", q: "Welcher Superheld ist Peter Parker?", a: "Spider-Man" },
  { cat: "Filme", q: "Wie heißt der grüne Oger?", a: "Shrek" },
  { cat: "Filme", q: "Wie heißt der Pirat aus Fluch der Karibik?", a: "Jack Sparrow" },
  { cat: "Filme", q: "In welchem Film sagt man 'Ich bin dein Vater'?", a: "Star Wars" },
  { cat: "Filme", q: "Wie heißt der Roboter aus Terminator?", a: "T-800" },

  { cat: "Allgemein", q: "Wie viele Kontinente gibt es?", a: "7" },
  { cat: "Allgemein", q: "Wie viele Tage hat ein Schaltjahr?", a: "366" },
  { cat: "Allgemein", q: "Was ist die Hauptstadt von Frankreich?", a: "Paris" },
  { cat: "Allgemein", q: "Wie viele Minuten hat eine Stunde?", a: "60" },
  { cat: "Allgemein", q: "Welches Tier ist das größte Landtier?", a: "Elefant" },
  { cat: "Allgemein", q: "Wie viele Farben hat ein Regenbogen klassisch?", a: "7" },
  { cat: "Allgemein", q: "Welcher Planet ist der Erde am nächsten?", a: "Venus oder Mars, je nach Position" },
  { cat: "Allgemein", q: "Wie heißt unser Sonnensystem-Zentrum?", a: "Die Sonne" },
  { cat: "Allgemein", q: "Was trinkt man aus einer Teekanne?", a: "Tee" },
  { cat: "Allgemein", q: "Wie viele Bundesländer hat Deutschland?", a: "16" },

  { cat: "Schätzen", q: "Wie viele Einwohner hat Deutschland ungefähr?", a: "ca. 84 Millionen" },
  { cat: "Schätzen", q: "Wie viele Knochen hat ein erwachsener Mensch ungefähr?", a: "206" },
  { cat: "Schätzen", q: "Wie viele Zähne hat ein erwachsener Mensch normalerweise?", a: "32" },
  { cat: "Schätzen", q: "Wie viele Sekunden hat eine Stunde?", a: "3600" },
  { cat: "Schätzen", q: "Wie viele Meter sind 1 Kilometer?", a: "1000" },
  { cat: "Schätzen", q: "Wie viele Tage hat ein normales Jahr?", a: "365" },
  { cat: "Schätzen", q: "Wie viele Planeten hat unser Sonnensystem?", a: "8" },
  { cat: "Schätzen", q: "Wie viele Spieler hat ein Fußballteam auf dem Feld?", a: "11" },
  { cat: "Schätzen", q: "Wie viele Karten hat ein normales UNO-Spiel ungefähr?", a: "108" },
  { cat: "Schätzen", q: "Wie viele Felder hat ein Schachbrett?", a: "64" },

  { cat: "Mathe", q: "Was ist 12 x 12?", a: "144" },
  { cat: "Mathe", q: "Was ist 9 x 7?", a: "63" },
  { cat: "Mathe", q: "Was ist die Quadratwurzel aus 81?", a: "9" },
  { cat: "Mathe", q: "Was ist 15 + 27?", a: "42" },
  { cat: "Mathe", q: "Was ist 100 geteilt durch 4?", a: "25" },
  { cat: "Mathe", q: "Was ist 7²?", a: "49" },
  { cat: "Mathe", q: "Was ist 3³?", a: "27" },
  { cat: "Mathe", q: "Was ist 50 Prozent von 200?", a: "100" },
  { cat: "Mathe", q: "Was ist 2 hoch 5?", a: "32" },
  { cat: "Mathe", q: "Was ist 0 mal 999?", a: "0" },

  { cat: "Geografie", q: "Was ist die Hauptstadt von Italien?", a: "Rom" },
  { cat: "Geografie", q: "Was ist die Hauptstadt von Spanien?", a: "Madrid" },
  { cat: "Geografie", q: "Welcher Fluss fließt durch Ägypten?", a: "Nil" },
  { cat: "Geografie", q: "Auf welchem Kontinent liegt Brasilien?", a: "Südamerika" },
  { cat: "Geografie", q: "Welches Land hat die Form eines Stiefels?", a: "Italien" },
  { cat: "Geografie", q: "Welche Stadt ist größer: Berlin oder München?", a: "Berlin" },
  { cat: "Geografie", q: "Wie heißt der höchste Berg der Welt?", a: "Mount Everest" },
  { cat: "Geografie", q: "In welchem Land liegt Tokio?", a: "Japan" },
  { cat: "Geografie", q: "Welche Hauptstadt hat Österreich?", a: "Wien" },
  { cat: "Geografie", q: "Welcher Ozean liegt zwischen Europa und Amerika?", a: "Atlantik" },

  { cat: "Internet", q: "Wofür steht LOL?", a: "Laughing out loud" },
  { cat: "Internet", q: "Was ist ein Meme?", a: "Ein Internet-Witz/Bild/Trend" },
  { cat: "Internet", q: "Welche Plattform ist bekannt für kurze Videos?", a: "TikTok" },
  { cat: "Internet", q: "Was bedeutet DM?", a: "Direct Message" },
  { cat: "Internet", q: "Was bedeutet POV?", a: "Point of View" },
  { cat: "Internet", q: "Was ist ein Streamer?", a: "Jemand, der live Inhalte sendet" },
  { cat: "Internet", q: "Welche Plattform nutzt man oft für Livestreams?", a: "Twitch" },
  { cat: "Internet", q: "Was bedeutet AFK?", a: "Away from keyboard" },
  { cat: "Internet", q: "Was bedeutet GG?", a: "Good Game" },
  { cat: "Internet", q: "Was bedeutet NPC im Internet-Slang?", a: "Jemand wirkt wie eine Nebenfigur/programmierte Figur" },

  { cat: "Memes", q: "Welches Tier ist Doge?", a: "Shiba Inu" },
  { cat: "Memes", q: "Was sagt man oft bei einem Fail?", a: "Bruh" },
  { cat: "Memes", q: "Welches Meme zeigt einen Frosch?", a: "Pepe" },
  { cat: "Memes", q: "Was bedeutet 'sus'?", a: "Verdächtig" },
  { cat: "Memes", q: "Aus welchem Spiel wurde 'sus' besonders bekannt?", a: "Among Us" },
  { cat: "Memes", q: "Was bedeutet 'ratio'?", a: "Mehr Gegenreaktionen als Zustimmung" },
  { cat: "Memes", q: "Was ist ein Rickroll?", a: "Unerwartet Rick Astley zeigen" },
  { cat: "Memes", q: "Welcher Song wird bei Rickroll benutzt?", a: "Never Gonna Give You Up" },
  { cat: "Memes", q: "Was bedeutet 'based'?", a: "Unabhängig/ehrlich/cool gemeint" },
  { cat: "Memes", q: "Was bedeutet 'cringe'?", a: "Fremdscham/peinlich" },
  // ===== TEIL 2 =====

{ cat: "Gaming", q: "Wie heißt die Insel in Fortnite?", a: "Battle Royale Insel / Fortnite Island" },
{ cat: "Gaming", q: "Welches Spiel hat den Charakter Steve?", a: "Minecraft" },
{ cat: "Gaming", q: "Wie heißt die Währung in Valorant?", a: "Credits" },
{ cat: "Gaming", q: "Welches Spiel ist bekannt für V-Bucks?", a: "Fortnite" },
{ cat: "Gaming", q: "In welchem Spiel gibt es Enderdrachen?", a: "Minecraft" },
{ cat: "Gaming", q: "Welche Farbe hat Luigi?", a: "Grün" },
{ cat: "Gaming", q: "Wie heißt die Firma hinter Xbox?", a: "Microsoft" },
{ cat: "Gaming", q: "Wie heißt der Würfel in Minecraft?", a: "Block" },
{ cat: "Gaming", q: "Welches Spiel hat die Map Summoner’s Rift?", a: "League of Legends" },
{ cat: "Gaming", q: "Wie heißt der Protagonist aus Zelda?", a: "Link" },

{ cat: "Anime", q: "Wie heißt der Lehrer von Naruto?", a: "Kakashi" },
{ cat: "Anime", q: "Wie heißt der Kapitän der Strohhutbande?", a: "Ruffy" },
{ cat: "Anime", q: "Aus welchem Anime ist Gojo?", a: "Jujutsu Kaisen" },
{ cat: "Anime", q: "Wie heißt der Dämonenjäger mit gelben Haaren?", a: "Zenitsu" },
{ cat: "Anime", q: "Wie heißt Eren mit Nachnamen?", a: "Jäger/Yeager" },
{ cat: "Anime", q: "Wie heißt das Notebook in Death Note?", a: "Death Note" },
{ cat: "Anime", q: "Wie heißt die Hauptfigur in Tokyo Ghoul?", a: "Ken Kaneki" },
{ cat: "Anime", q: "Aus welchem Anime ist Luffy?", a: "One Piece" },
{ cat: "Anime", q: "Wie heißt Narutos Sohn?", a: "Boruto" },
{ cat: "Anime", q: "Welche Haarfarbe hat Goku meistens?", a: "Schwarz" },

{ cat: "Filme", q: "Wie heißt der blaue Alien-Film?", a: "Avatar" },
{ cat: "Filme", q: "Welcher Held benutzt einen Hammer?", a: "Thor" },
{ cat: "Filme", q: "Wie heißt der König der Löwen?", a: "Mufasa" },
{ cat: "Filme", q: "Wie heißt Elsas Schwester?", a: "Anna" },
{ cat: "Filme", q: "Welcher Film hat Minions?", a: "Ich – Einfach unverbesserlich" },
{ cat: "Filme", q: "Wie heißt Batmans Butler?", a: "Alfred" },
{ cat: "Filme", q: "Welcher Held trägt einen Schild?", a: "Captain America" },
{ cat: "Filme", q: "Wie heißt der Cowboy aus Toy Story?", a: "Woody" },
{ cat: "Filme", q: "Wie heißt der Space Ranger aus Toy Story?", a: "Buzz Lightyear" },
{ cat: "Filme", q: "Welcher Film hat Dinosaurier-Park?", a: "Jurassic Park" },

{ cat: "Allgemein", q: "Wie viele Stunden hat ein Tag?", a: "24" },
{ cat: "Allgemein", q: "Wie viele Sekunden hat eine Minute?", a: "60" },
{ cat: "Allgemein", q: "Welche Farbe entsteht aus Blau und Gelb?", a: "Grün" },
{ cat: "Allgemein", q: "Was trinken Kühe?", a: "Wasser" },
{ cat: "Allgemein", q: "Wie viele Monate hat ein Jahr?", a: "12" },
{ cat: "Allgemein", q: "Was ist gefrorenes Wasser?", a: "Eis" },
{ cat: "Allgemein", q: "Welches Tier miaut?", a: "Katze" },
{ cat: "Allgemein", q: "Wie viele Beine hat eine Spinne?", a: "8" },
{ cat: "Allgemein", q: "Wie heißt unser Planet?", a: "Erde" },
{ cat: "Allgemein", q: "Was ist heißer: Sonne oder Mond?", a: "Sonne" },

{ cat: "Schätzen", q: "Wie viele Tasten hat ein Klavier ungefähr?", a: "88" },
{ cat: "Schätzen", q: "Wie viele Spieler sind in einem Volleyballteam auf dem Feld?", a: "6" },
{ cat: "Schätzen", q: "Wie viele Liter hat ein Kubikmeter Wasser?", a: "1000" },
{ cat: "Schätzen", q: "Wie viele Minuten hat ein Tag?", a: "1440" },
{ cat: "Schätzen", q: "Wie viele cm hat 1 Meter?", a: "100" },
{ cat: "Schätzen", q: "Wie viele Buchstaben hat das Alphabet?", a: "26" },
{ cat: "Schätzen", q: "Wie viele Leben hat eine Katze laut Sprichwort?", a: "7" },
{ cat: "Schätzen", q: "Wie viele Herzen hat ein Oktopus?", a: "3" },
{ cat: "Schätzen", q: "Wie viele Spieler sind in einem LoL Team?", a: "5" },
{ cat: "Schätzen", q: "Wie viele Farben hat die deutsche Flagge?", a: "3" },

{ cat: "Mathe", q: "Was ist 8 x 8?", a: "64" },
{ cat: "Mathe", q: "Was ist 100 - 45?", a: "55" },
{ cat: "Mathe", q: "Was ist 11 x 11?", a: "121" },
{ cat: "Mathe", q: "Was ist 90 geteilt durch 10?", a: "9" },
{ cat: "Mathe", q: "Was ist 5 hoch 2?", a: "25" },
{ cat: "Mathe", q: "Was ist die Hälfte von 50?", a: "25" },
{ cat: "Mathe", q: "Was ist 14 + 28?", a: "42" },
{ cat: "Mathe", q: "Was ist 3 x 15?", a: "45" },
{ cat: "Mathe", q: "Was ist 99 + 1?", a: "100" },
{ cat: "Mathe", q: "Was ist 81 geteilt durch 9?", a: "9" },

{ cat: "Geografie", q: "Welche Hauptstadt hat England?", a: "London" },
{ cat: "Geografie", q: "In welchem Land liegt Berlin?", a: "Deutschland" },
{ cat: "Geografie", q: "Welcher Kontinent ist Afrika?", a: "Afrika" },
{ cat: "Geografie", q: "Welche Hauptstadt hat Japan?", a: "Tokio" },
{ cat: "Geografie", q: "Welche Sprache spricht man in Spanien?", a: "Spanisch" },
{ cat: "Geografie", q: "Welche Hauptstadt hat Polen?", a: "Warschau" },
{ cat: "Geografie", q: "Welcher Kontinent ist Australien?", a: "Australien" },
{ cat: "Geografie", q: "Welches Land hat Ahornblatt-Flagge?", a: "Kanada" },
{ cat: "Geografie", q: "Welches Land ist für Pizza bekannt?", a: "Italien" },
{ cat: "Geografie", q: "Welches Land hat die Hauptstadt Paris?", a: "Frankreich" },

{ cat: "Internet", q: "Welche Plattform gehört zu Amazon?", a: "Twitch" },
{ cat: "Internet", q: "Was bedeutet IRL?", a: "In Real Life" },
{ cat: "Internet", q: "Was bedeutet OP im Gaming?", a: "Overpowered" },
{ cat: "Internet", q: "Was bedeutet EZ?", a: "Easy" },
{ cat: "Internet", q: "Was bedeutet FPS?", a: "Frames per second" },
{ cat: "Internet", q: "Was bedeutet Ping im Gaming?", a: "Verbindungslatenz" },
{ cat: "Internet", q: "Was bedeutet Ban?", a: "Ausschluss/Sperre" },
{ cat: "Internet", q: "Was ist Discord?", a: "Chat-/Voice-Plattform" },
{ cat: "Internet", q: "Was bedeutet Mod?", a: "Moderator" },
{ cat: "Internet", q: "Was bedeutet Streamsnipen?", a: "Streamer absichtlich ingame finden" },

{ cat: "Memes", q: "Was bedeutet 'No cap'?", a: "Kein Witz / ernst gemeint" },
{ cat: "Memes", q: "Was bedeutet 'mid'?", a: "Mittelmäßig" },
{ cat: "Memes", q: "Was bedeutet 'W' im Chat?", a: "Win / stark" },
{ cat: "Memes", q: "Was bedeutet 'L' im Chat?", a: "Loss / schlecht" },
{ cat: "Memes", q: "Was bedeutet 'NPC Energy'?", a: "Jemand wirkt emotionslos/gleich" },
{ cat: "Memes", q: "Was bedeutet 'Sigma' im Internet?", a: "Selbstständiger Lone Wolf Meme" },
{ cat: "Memes", q: "Was bedeutet 'GYAT'?", a: "Slang für große Kurven" },
{ cat: "Memes", q: "Was bedeutet 'Sheesh'?", a: "Ausdruck für Beeindruckung" },
{ cat: "Memes", q: "Was bedeutet 'Bing Chilling' Meme?", a: "John Cena Meme" },
{ cat: "Memes", q: "Was bedeutet 'Touch grass'?", a: "Geh mal raus" },
// ===== TEIL 3 =====

{ cat: "Gaming", q: "Welches Spiel hat den Nether?", a: "Minecraft" },
{ cat: "Gaming", q: "Wie heißt der gelbe Kreis aus Pac-Man?", a: "Pac-Man" },
{ cat: "Gaming", q: "In welchem Spiel gibt es Tilted Towers?", a: "Fortnite" },
{ cat: "Gaming", q: "Welche Farbe hat der Among Us Crewmate standardmäßig oft?", a: "Rot" },
{ cat: "Gaming", q: "Wie heißt das Auto-Fußball-Spiel?", a: "Rocket League" },
{ cat: "Gaming", q: "Welche Firma macht Nintendo Switch?", a: "Nintendo" },
{ cat: "Gaming", q: "Wie heißt die Karte in Minecraft ohne Mods?", a: "Overworld" },
{ cat: "Gaming", q: "In welchem Spiel gibt es Agenten?", a: "Valorant" },
{ cat: "Gaming", q: "Welche Waffe nutzt der AWP-Spieler oft?", a: "Sniper" },
{ cat: "Gaming", q: "Welches Spiel hat Zombies und Perks?", a: "Call of Duty Zombies" },

{ cat: "Anime", q: "Wie heißt der Rivale von Naruto?", a: "Sasuke" },
{ cat: "Anime", q: "Wie heißt der Schöpfer der Titanen-Manga?", a: "Hajime Isayama" },
{ cat: "Anime", q: "Wie heißt die stärkste Form von Goku oft?", a: "Ultra Instinct" },
{ cat: "Anime", q: "Wie heißt L aus Death Note?", a: "L Lawliet" },
{ cat: "Anime", q: "Wie heißt Zoros Schwertstil?", a: "Drei-Schwerter-Stil" },
{ cat: "Anime", q: "Aus welchem Anime ist Nezuko?", a: "Demon Slayer" },
{ cat: "Anime", q: "Wie heißt der Sensei von Deku?", a: "All Might" },
{ cat: "Anime", q: "Wie heißt der Anime mit den Piraten?", a: "One Piece" },
{ cat: "Anime", q: "Wie heißt der König der Ameisen in Hunter x Hunter?", a: "Meruem" },
{ cat: "Anime", q: "Wie heißt Saitamas Anime?", a: "One Punch Man" },

{ cat: "Filme", q: "Wie heißt der blaue Igel-Film?", a: "Sonic" },
{ cat: "Filme", q: "Wie heißt Iron Mans echter Name?", a: "Tony Stark" },
{ cat: "Filme", q: "Wie heißt Hulks menschliche Form?", a: "Bruce Banner" },
{ cat: "Filme", q: "Wie heißt der Joker Gegner von Batman?", a: "Batman" },
{ cat: "Filme", q: "Wie heißt der Fisch aus Findet Nemo?", a: "Nemo" },
{ cat: "Filme", q: "Wie heißt der Panda aus Kung Fu Panda?", a: "Po" },
{ cat: "Filme", q: "Welcher Film hat den Charakter Olaf?", a: "Frozen / Die Eiskönigin" },
{ cat: "Filme", q: "Wie heißt der Sheriff aus Cars?", a: "Lightning McQueen" },
{ cat: "Filme", q: "Welcher Film hat den Charakter Gru?", a: "Ich – Einfach unverbesserlich" },
{ cat: "Filme", q: "Wie heißt der Junge aus Kevin allein zu Haus?", a: "Kevin" },

{ cat: "Allgemein", q: "Wie viele Tage hat der Februar normalerweise?", a: "28" },
{ cat: "Allgemein", q: "Welche Farbe hat Blut meistens?", a: "Rot" },
{ cat: "Allgemein", q: "Wie nennt man gefrorenen Regen?", a: "Hagel" },
{ cat: "Allgemein", q: "Welches Organ pumpt Blut?", a: "Herz" },
{ cat: "Allgemein", q: "Was braucht Feuer zum Brennen?", a: "Sauerstoff" },
{ cat: "Allgemein", q: "Welche Jahreszeit kommt nach Sommer?", a: "Herbst" },
{ cat: "Allgemein", q: "Wie viele Finger haben Menschen normalerweise?", a: "10" },
{ cat: "Allgemein", q: "Welches Tier legt Eier?", a: "Huhn" },
{ cat: "Allgemein", q: "Was ist das Gegenteil von kalt?", a: "Heiß/Warm" },
{ cat: "Allgemein", q: "Welcher Monat kommt nach März?", a: "April" },

{ cat: "Schätzen", q: "Wie viele Stunden hat eine Woche?", a: "168" },
{ cat: "Schätzen", q: "Wie viele Sekunden hat ein Tag?", a: "86400" },
{ cat: "Schätzen", q: "Wie viele cm hat 1 Zoll ungefähr?", a: "2,54" },
{ cat: "Schätzen", q: "Wie viele Spieler hat ein Basketballteam auf dem Feld?", a: "5" },
{ cat: "Schätzen", q: "Wie viele Monde hat die Erde?", a: "1" },
{ cat: "Schätzen", q: "Wie viele Kontinente gibt es?", a: "7" },
{ cat: "Schätzen", q: "Wie viele Farben hat die Google-Logo Schrift?", a: "4 Farben" },
{ cat: "Schätzen", q: "Wie viele Staffeln hat Breaking Bad?", a: "5" },
{ cat: "Schätzen", q: "Wie viele Mitglieder hat die Strohhutbande ungefähr aktuell?", a: "10" },
{ cat: "Schätzen", q: "Wie viele Felder hat ein Sudoku?", a: "81" },

{ cat: "Mathe", q: "Was ist 13 x 3?", a: "39" },
{ cat: "Mathe", q: "Was ist 144 geteilt durch 12?", a: "12" },
{ cat: "Mathe", q: "Was ist 25 + 75?", a: "100" },
{ cat: "Mathe", q: "Was ist 7 x 6?", a: "42" },
{ cat: "Mathe", q: "Was ist die Wurzel aus 49?", a: "7" },
{ cat: "Mathe", q: "Was ist 10 Prozent von 500?", a: "50" },
{ cat: "Mathe", q: "Was ist 6²?", a: "36" },
{ cat: "Mathe", q: "Was ist 200 - 99?", a: "101" },
{ cat: "Mathe", q: "Was ist 5 x 5 x 5?", a: "125" },
{ cat: "Mathe", q: "Was ist 18 + 24?", a: "42" },

{ cat: "Geografie", q: "Welche Hauptstadt hat Russland?", a: "Moskau" },
{ cat: "Geografie", q: "Welche Hauptstadt hat Kanada?", a: "Ottawa" },
{ cat: "Geografie", q: "Welcher Kontinent ist Europa?", a: "Europa" },
{ cat: "Geografie", q: "Welche Hauptstadt hat China?", a: "Peking" },
{ cat: "Geografie", q: "In welchem Land liegt Dubai?", a: "Vereinigte Arabische Emirate" },
{ cat: "Geografie", q: "Welches Land hat die Form eines Hexagons auf Karten oft?", a: "Frankreich" },
{ cat: "Geografie", q: "Welche Hauptstadt hat Griechenland?", a: "Athen" },
{ cat: "Geografie", q: "Welches Meer liegt zwischen Europa und Afrika?", a: "Mittelmeer" },
{ cat: "Geografie", q: "Wie heißt die Hauptstadt von Türkei?", a: "Ankara" },
{ cat: "Geografie", q: "Welches Land hat die meisten Einwohner?", a: "Indien oder China" },

{ cat: "Internet", q: "Welche App ist bekannt für Reels?", a: "Instagram" },
{ cat: "Internet", q: "Was bedeutet 'viral gehen'?", a: "Sich schnell verbreiten" },
{ cat: "Internet", q: "Was ist ein Hashtag?", a: "Schlagwort mit #" },
{ cat: "Internet", q: "Welche Plattform gehört Meta?", a: "Instagram/Facebook/WhatsApp" },
{ cat: "Internet", q: "Was bedeutet WLAN?", a: "Drahtloses Netzwerk" },
{ cat: "Internet", q: "Was bedeutet USB?", a: "Universal Serial Bus" },
{ cat: "Internet", q: "Was ist YouTube hauptsächlich?", a: "Videoplattform" },
{ cat: "Internet", q: "Was bedeutet VPN?", a: "Virtuelles privates Netzwerk" },
{ cat: "Internet", q: "Was bedeutet 404?", a: "Seite nicht gefunden" },
{ cat: "Internet", q: "Welche Plattform nutzt man für Server-Chats?", a: "Discord" },

{ cat: "Memes", q: "Was bedeutet 'Let him cook'?", a: "Lass ihn machen" },
{ cat: "Memes", q: "Was bedeutet 'copium'?", a: "Sich etwas schönreden" },
{ cat: "Memes", q: "Was bedeutet 'Rizz'?", a: "Charisma/Flirt-Skill" },
{ cat: "Memes", q: "Was bedeutet 'skibidi' meist nur noch?", a: "Brainrot Meme" },
{ cat: "Memes", q: "Was bedeutet 'delulu'?", a: "Delusional/verrückt verliebt" },
{ cat: "Memes", q: "Was bedeutet 'bro is cooked'?", a: "Er ist verloren" },
{ cat: "Memes", q: "Was bedeutet 'main character energy'?", a: "Jemand wirkt wie Hauptfigur" },
{ cat: "Memes", q: "Was bedeutet 'goofy ahh'?", a: "Dumm/lustig aussehend" },
{ cat: "Memes", q: "Was bedeutet 'blud'?", a: "Bro/Digga" },
{ cat: "Memes", q: "Was bedeutet 'nah I'd win'?", a: "Meme aus Jujutsu Kaisen" },
// ===== TEIL 4 =====

{ cat: "Gaming", q: "Welches Spiel hat den Modus Creative?", a: "Minecraft" },
{ cat: "Gaming", q: "Wie heißt die Bombe in Counter-Strike?", a: "C4" },
{ cat: "Gaming", q: "Welche Farbe hat ein Legendary Item oft?", a: "Gold" },
{ cat: "Gaming", q: "Wie heißt das bekannte Survival-Spiel mit Dinos?", a: "ARK" },
{ cat: "Gaming", q: "Welche Firma entwickelte GTA?", a: "Rockstar Games" },
{ cat: "Gaming", q: "Wie heißt die Hauptstadt in Clash Royale?", a: "King Tower/Königsturm" },
{ cat: "Gaming", q: "Welches Spiel hat Creeper und Enderman?", a: "Minecraft" },
{ cat: "Gaming", q: "Wie heißt die Heil-Items in Fortnite?", a: "Shield/Medkit" },
{ cat: "Gaming", q: "Welches Spiel hat Agents wie Jett?", a: "Valorant" },
{ cat: "Gaming", q: "Wie heißt die Konsole vor der PS5?", a: "PS4" },

{ cat: "Anime", q: "Wie heißt Narutos Vater?", a: "Minato" },
{ cat: "Anime", q: "Wie heißt die Organisation von Itachi?", a: "Akatsuki" },
{ cat: "Anime", q: "Aus welchem Anime ist Levi?", a: "Attack on Titan" },
{ cat: "Anime", q: "Wie heißt die Schwester von Tanjiro?", a: "Nezuko" },
{ cat: "Anime", q: "Wie heißt das Schiff von Ruffy?", a: "Thousand Sunny" },
{ cat: "Anime", q: "Wie heißt der Lehrer mit verbundenen Augen?", a: "Gojo" },
{ cat: "Anime", q: "Wie heißt die stärkste Titanform von Eren?", a: "Founding Titan/Urtitan" },
{ cat: "Anime", q: "Aus welchem Anime ist Killua?", a: "Hunter x Hunter" },
{ cat: "Anime", q: "Wie heißt der Dämon in Chainsaw Man?", a: "Pochita" },
{ cat: "Anime", q: "Wie heißt der Anime mit den Ninjas?", a: "Naruto" },

{ cat: "Filme", q: "Wie heißt der schwarze Panther Held?", a: "Black Panther" },
{ cat: "Filme", q: "Wie heißt der Hauptcharakter in Titanic?", a: "Jack Dawson" },
{ cat: "Filme", q: "Welcher Film hat einen sprechenden Esel?", a: "Shrek" },
{ cat: "Filme", q: "Wie heißt der Löwe aus Madagascar?", a: "Alex" },
{ cat: "Filme", q: "Wie heißt der Panda aus Kung Fu Panda?", a: "Po" },
{ cat: "Filme", q: "Welcher Held schrumpft sich klein?", a: "Ant-Man" },
{ cat: "Filme", q: "Wie heißt der Gott des Donners?", a: "Thor" },
{ cat: "Filme", q: "Welcher Film hat den blauen Alien Jake Sully?", a: "Avatar" },
{ cat: "Filme", q: "Wie heißt der Cowboy aus Toy Story?", a: "Woody" },
{ cat: "Filme", q: "Wie heißt der Sheriff-Auto aus Cars?", a: "Lightning McQueen" },

{ cat: "Allgemein", q: "Welcher Tag kommt nach Freitag?", a: "Samstag" },
{ cat: "Allgemein", q: "Wie viele Stunden hat eine Woche?", a: "168" },
{ cat: "Allgemein", q: "Was ist schwerer: 1kg Federn oder 1kg Eisen?", a: "Beides gleich" },
{ cat: "Allgemein", q: "Welches Tier bellt?", a: "Hund" },
{ cat: "Allgemein", q: "Welche Farbe hat Gras?", a: "Grün" },
{ cat: "Allgemein", q: "Was ist das Gegenteil von langsam?", a: "Schnell" },
{ cat: "Allgemein", q: "Wie viele Augen hat ein Mensch normalerweise?", a: "2" },
{ cat: "Allgemein", q: "Was ist das Gegenteil von Tag?", a: "Nacht" },
{ cat: "Allgemein", q: "Welcher Monat hat Weihnachten?", a: "Dezember" },
{ cat: "Allgemein", q: "Wie viele Wochen hat ein Jahr ungefähr?", a: "52" },

{ cat: "Schätzen", q: "Wie viele Spieler hat ein Handballteam auf dem Feld?", a: "7" },
{ cat: "Schätzen", q: "Wie viele Farben hat die Regenbogenflagge oft?", a: "6" },
{ cat: "Schätzen", q: "Wie viele Staffeln hat Naruto ungefähr mit Shippuden?", a: "über 20" },
{ cat: "Schätzen", q: "Wie viele Knochen hat eine Hand ungefähr?", a: "27" },
{ cat: "Schätzen", q: "Wie viele Liter Blut hat ein Mensch ungefähr?", a: "5-6 Liter" },
{ cat: "Schätzen", q: "Wie viele Planeten sind größer als die Erde?", a: "4" },
{ cat: "Schätzen", q: "Wie viele Sekunden sind 10 Minuten?", a: "600" },
{ cat: "Schätzen", q: "Wie viele Karten hat ein Skatblatt?", a: "32" },
{ cat: "Schätzen", q: "Wie viele Bundesstaaten hat Amerika?", a: "50" },
{ cat: "Schätzen", q: "Wie viele Buchstaben hat das Wort 'Banane'?", a: "6" },

{ cat: "Mathe", q: "Was ist 16 x 2?", a: "32" },
{ cat: "Mathe", q: "Was ist 144 + 56?", a: "200" },
{ cat: "Mathe", q: "Was ist 7 + 35?", a: "42" },
{ cat: "Mathe", q: "Was ist 8²?", a: "64" },
{ cat: "Mathe", q: "Was ist 250 geteilt durch 5?", a: "50" },
{ cat: "Mathe", q: "Was ist 19 + 23?", a: "42" },
{ cat: "Mathe", q: "Was ist 5 x 9?", a: "45" },
{ cat: "Mathe", q: "Was ist 20 Prozent von 100?", a: "20" },
{ cat: "Mathe", q: "Was ist 1000 - 1?", a: "999" },
{ cat: "Mathe", q: "Was ist 4³?", a: "64" },

{ cat: "Geografie", q: "Welche Hauptstadt hat Portugal?", a: "Lissabon" },
{ cat: "Geografie", q: "Welche Hauptstadt hat Schweden?", a: "Stockholm" },
{ cat: "Geografie", q: "Welche Hauptstadt hat Norwegen?", a: "Oslo" },
{ cat: "Geografie", q: "Welches Land hat die Hauptstadt Bern?", a: "Schweiz" },
{ cat: "Geografie", q: "Welches Land ist bekannt für Sushi?", a: "Japan" },
{ cat: "Geografie", q: "Welches Land hat die Form eines Stiefels?", a: "Italien" },
{ cat: "Geografie", q: "Welcher Kontinent liegt südlich von Europa?", a: "Afrika" },
{ cat: "Geografie", q: "Welche Hauptstadt hat Niederlande?", a: "Amsterdam" },
{ cat: "Geografie", q: "Welcher Kontinent ist der größte?", a: "Asien" },
{ cat: "Geografie", q: "Wie heißt die Hauptstadt von Belgien?", a: "Brüssel" },

{ cat: "Internet", q: "Was bedeutet 'sub' auf Twitch?", a: "Abonnement" },
{ cat: "Internet", q: "Was bedeutet 'clippen'?", a: "Ausschnitt speichern" },
{ cat: "Internet", q: "Welche Plattform nutzt man für Kurzvideos?", a: "TikTok" },
{ cat: "Internet", q: "Was bedeutet 'laggen'?", a: "Verzögerung haben" },
{ cat: "Internet", q: "Was bedeutet 'buffen' im Gaming?", a: "Stärker machen" },
{ cat: "Internet", q: "Was bedeutet 'nerfen'?", a: "Schwächer machen" },
{ cat: "Internet", q: "Was ist ein Emoji?", a: "Digitales Symbol/Gesicht" },
{ cat: "Internet", q: "Was bedeutet 'offline gehen'?", a: "Stream/Internet beenden" },
{ cat: "Internet", q: "Was bedeutet 'Streamer setup'?", a: "Streaming-Ausrüstung" },
{ cat: "Internet", q: "Was ist OBS?", a: "Streaming-/Recording-Programm" },

{ cat: "Memes", q: "Was bedeutet 'he fell off'?", a: "Jemand ist schlechter geworden" },
{ cat: "Memes", q: "Was bedeutet 'brainrot'?", a: "Internet-Humor macht Gehirn kaputt" },
{ cat: "Memes", q: "Was bedeutet 'caught in 4k'?", a: "Erwischt worden" },
{ cat: "Memes", q: "Was bedeutet 'W aura'?", a: "Gute Ausstrahlung" },
{ cat: "Memes", q: "Was bedeutet 'negative aura'?", a: "Peinliche Ausstrahlung" },
{ cat: "Memes", q: "Was bedeutet 'unc status'?", a: "Sieht alt aus" },
{ cat: "Memes", q: "Was bedeutet 'sigma grindset'?", a: "Meme über Hustle-Mindset" },
{ cat: "Memes", q: "Was bedeutet 'nah bro is done'?", a: "Er ist verloren" },
{ cat: "Memes", q: "Was bedeutet 'we got ___ before GTA 6'?", a: "Meme über lange Wartezeit" },
{ cat: "Memes", q: "Was bedeutet 'NPC dialogue'?", a: "Klingt wie Standarddialog" },
// ===== TEIL 5 =====

{ cat: "Gaming", q: "Wie heißt die stärkste Rüstung in Minecraft?", a: "Netherite" },
{ cat: "Gaming", q: "Welches Spiel hat den Gulag?", a: "Call of Duty Warzone" },
{ cat: "Gaming", q: "Wie heißt das bekannte Tanz-Emote aus Fortnite?", a: "Default Dance" },
{ cat: "Gaming", q: "Wie heißt die Bombe entschärfen Map in CS?", a: "Bomb Defusal" },
{ cat: "Gaming", q: "Welches Spiel hat die Legende Bloodhound?", a: "Apex Legends" },
{ cat: "Gaming", q: "Wie heißt der blaue Drache in Pokémon?", a: "Dragonite/Garados je nach Antwort" },
{ cat: "Gaming", q: "Welche Firma entwickelte Minecraft ursprünglich?", a: "Mojang" },
{ cat: "Gaming", q: "Wie heißt die Welt in Zelda?", a: "Hyrule" },
{ cat: "Gaming", q: "Welches Spiel hat die Waffe Vandal?", a: "Valorant" },
{ cat: "Gaming", q: "Wie heißt die grüne Pflanze gegen Zombies?", a: "Peashooter" },

{ cat: "Anime", q: "Wie heißt der Vater von Gon?", a: "Ging" },
{ cat: "Anime", q: "Wie heißt die Katze aus Dragon Ball?", a: "Beerus" },
{ cat: "Anime", q: "Welche Farbe haben Gokus Haare als Super Saiyajin?", a: "Gold/Gelb" },
{ cat: "Anime", q: "Wie heißt der Schwertkämpfer aus One Piece?", a: "Zoro" },
{ cat: "Anime", q: "Wie heißt der Hauptcharakter aus Bleach?", a: "Ichigo" },
{ cat: "Anime", q: "Aus welchem Anime ist Rem?", a: "Re:Zero" },
{ cat: "Anime", q: "Wie heißt die Kraft in Naruto?", a: "Chakra" },
{ cat: "Anime", q: "Wie heißt der Titanen-Anime?", a: "Attack on Titan" },
{ cat: "Anime", q: "Wie heißt die Organisation aus Jujutsu Kaisen?", a: "Jujutsu Schule/Gesellschaft" },
{ cat: "Anime", q: "Wie heißt der stärkste Zauberer oft in JJK?", a: "Gojo" },

{ cat: "Filme", q: "Wie heißt der Hauptcharakter aus Matrix?", a: "Neo" },
{ cat: "Filme", q: "Welcher Film hat den Charakter Simba?", a: "König der Löwen" },
{ cat: "Filme", q: "Wie heißt der Schneemann aus Frozen?", a: "Olaf" },
{ cat: "Filme", q: "Wie heißt der Zauberermentor von Harry?", a: "Dumbledore" },
{ cat: "Filme", q: "Wie heißt der rote Blitzheld?", a: "Flash" },
{ cat: "Filme", q: "Welcher Held hat Krallen aus Adamantium?", a: "Wolverine" },
{ cat: "Filme", q: "Wie heißt der grüne Held der Avengers?", a: "Hulk" },
{ cat: "Filme", q: "Wie heißt der Planet aus Avatar?", a: "Pandora" },
{ cat: "Filme", q: "Welcher Film hat sprechende Autos?", a: "Cars" },
{ cat: "Filme", q: "Wie heißt der Clownfisch aus Nemo?", a: "Nemo" },

{ cat: "Allgemein", q: "Wie viele Minuten hat ein Tag?", a: "1440" },
{ cat: "Allgemein", q: "Was ist das Gegenteil von hell?", a: "Dunkel" },
{ cat: "Allgemein", q: "Welches Tier kann fliegen?", a: "Vogel" },
{ cat: "Allgemein", q: "Welche Farbe hat eine Banane meistens?", a: "Gelb" },
{ cat: "Allgemein", q: "Wie nennt man Wasser in fest?", a: "Eis" },
{ cat: "Allgemein", q: "Wie viele Stunden hat ein halber Tag?", a: "12" },
{ cat: "Allgemein", q: "Welches Tier sagt muh?", a: "Kuh" },
{ cat: "Allgemein", q: "Wie viele Räder hat ein Fahrrad?", a: "2" },
{ cat: "Allgemein", q: "Was ist das Gegenteil von groß?", a: "Klein" },
{ cat: "Allgemein", q: "Welcher Monat beginnt mit J?", a: "Januar/Juni/Juli" },

{ cat: "Schätzen", q: "Wie viele Tage hat eine Woche?", a: "7" },
{ cat: "Schätzen", q: "Wie viele Stunden schläft ein Mensch ungefähr?", a: "6-8 Stunden" },
{ cat: "Schätzen", q: "Wie viele Farben hat ein Schachbrett?", a: "2" },
{ cat: "Schätzen", q: "Wie viele Spieler sind in einer Fußballmannschaft insgesamt?", a: "11" },
{ cat: "Schätzen", q: "Wie viele Staffeln hat One Piece ungefähr?", a: "über 20" },
{ cat: "Schätzen", q: "Wie viele Episoden hat Naruto ungefähr?", a: "über 700 mit Shippuden" },
{ cat: "Schätzen", q: "Wie viele Herzen hat ein Mensch?", a: "1" },
{ cat: "Schätzen", q: "Wie viele Länder gibt es ungefähr?", a: "ca. 195" },
{ cat: "Schätzen", q: "Wie viele Jahre sind ein Jahrzehnt?", a: "10" },
{ cat: "Schätzen", q: "Wie viele Monate sind ein Quartal?", a: "3" },

{ cat: "Mathe", q: "Was ist 22 + 20?", a: "42" },
{ cat: "Mathe", q: "Was ist 9²?", a: "81" },
{ cat: "Mathe", q: "Was ist 7 x 8?", a: "56" },
{ cat: "Mathe", q: "Was ist 300 geteilt durch 3?", a: "100" },
{ cat: "Mathe", q: "Was ist die Hälfte von 90?", a: "45" },
{ cat: "Mathe", q: "Was ist 6 x 7?", a: "42" },
{ cat: "Mathe", q: "Was ist 111 + 111?", a: "222" },
{ cat: "Mathe", q: "Was ist 10 x 10?", a: "100" },
{ cat: "Mathe", q: "Was ist 15²?", a: "225" },
{ cat: "Mathe", q: "Was ist 1 Prozent von 100?", a: "1" },

{ cat: "Geografie", q: "Welche Hauptstadt hat USA?", a: "Washington D.C." },
{ cat: "Geografie", q: "Welche Hauptstadt hat Australien?", a: "Canberra" },
{ cat: "Geografie", q: "Welcher Kontinent ist Afrika?", a: "Afrika" },
{ cat: "Geografie", q: "Welche Hauptstadt hat Dänemark?", a: "Kopenhagen" },
{ cat: "Geografie", q: "Welches Land ist bekannt für Anime?", a: "Japan" },
{ cat: "Geografie", q: "Welche Hauptstadt hat Finnland?", a: "Helsinki" },
{ cat: "Geografie", q: "Welches Land hat die meisten Inseln?", a: "Schweden" },
{ cat: "Geografie", q: "Welcher Kontinent ist der kleinste?", a: "Australien" },
{ cat: "Geografie", q: "Welche Hauptstadt hat Irland?", a: "Dublin" },
{ cat: "Geografie", q: "Welche Hauptstadt hat Ägypten?", a: "Kairo" },

{ cat: "Internet", q: "Was bedeutet 'YT'?", a: "YouTube" },
{ cat: "Internet", q: "Was bedeutet 'streamen'?", a: "Live senden" },
{ cat: "Internet", q: "Was ist ein Browser?", a: "Programm für Webseiten" },
{ cat: "Internet", q: "Welche Plattform nutzt man oft für Memes?", a: "Reddit" },
{ cat: "Internet", q: "Was bedeutet 'Follower'?", a: "Jemand folgt einem Account" },
{ cat: "Internet", q: "Was bedeutet 'viral'?", a: "Verbreitet sich schnell" },
{ cat: "Internet", q: "Was bedeutet 'Chat spam'?", a: "Viele Nachrichten schnell senden" },
{ cat: "Internet", q: "Was bedeutet 'Alt Account'?", a: "Zweitaccount" },
{ cat: "Internet", q: "Was bedeutet 'Mute'?", a: "Stumm schalten" },
{ cat: "Internet", q: "Was ist ein GIF?", a: "Animiertes Bild" },

{ cat: "Memes", q: "Was bedeutet 'bro thinks he is him'?", a: "Jemand hält sich für krass" },
{ cat: "Memes", q: "Was bedeutet 'yapping'?", a: "Zu viel reden" },
{ cat: "Memes", q: "Was bedeutet 'goat'?", a: "Greatest of all time" },
{ cat: "Memes", q: "Was bedeutet 'cap'?", a: "Lüge" },
{ cat: "Memes", q: "Was bedeutet 'glazing'?", a: "Übertrieben dick reiten/loben" },
{ cat: "Memes", q: "Was bedeutet 'cooked'?", a: "Verloren/erledigt" },
{ cat: "Memes", q: "Was bedeutet 'aura farming'?", a: "Cool wirken wollen" },
{ cat: "Memes", q: "Was bedeutet 'mogging'?", a: "Jemanden optisch dominieren" },
{ cat: "Memes", q: "Was bedeutet 'drip'?", a: "Stylisches Outfit" },
{ cat: "Memes", q: "Was bedeutet 'sigma face'?", a: "Ernstes cooles Meme-Gesicht" },
// ===== UNIQUE / SCHWIERIGER / RAGEBAIT =====

{ cat: "Gaming", q: "Welches Spiel war zuerst da: Minecraft oder Fortnite?", a: "Minecraft" },
{ cat: "Gaming", q: "Welche Farbe hat die seltenste Among Us Rolle oft?", a: "Keine feste / abhängig von Mods" },
{ cat: "Gaming", q: "Wie heißt die Welt unter dem Nether?", a: "End" },
{ cat: "Gaming", q: "Welches Spiel machte den Battle Pass extrem populär?", a: "Fortnite" },
{ cat: "Gaming", q: "Welche Konsole erschien zuerst: PS4 oder Nintendo Switch?", a: "PS4" },
{ cat: "Gaming", q: "Wie viele Spieler sind in einem Valorant Team?", a: "5" },
{ cat: "Gaming", q: "Welches Spiel hat den Modus Ranked 2v2 mit Eiern?", a: "Brawlhalla" },
{ cat: "Gaming", q: "Welche Farbe haben Mythic Items oft?", a: "Gold" },
{ cat: "Gaming", q: "Welches Spiel hat den Charakter Revenant?", a: "Apex Legends" },
{ cat: "Gaming", q: "Wie heißt der Würfel-Boss in Minecraft Dungeons?", a: "Arch-Illager/Heart of Ender" },

{ cat: "Anime", q: "Wie heißt das Auge von Kakashi?", a: "Sharingan" },
{ cat: "Anime", q: "Welcher Anime hat die meisten Folgen?", a: "Sazae-san" },
{ cat: "Anime", q: "Wie heißt Gokus Saiyajin Name?", a: "Kakarot" },
{ cat: "Anime", q: "Wer tötet Ace?", a: "Akainu" },
{ cat: "Anime", q: "Wie heißt der stärkste Hunter in Hunter x Hunter oft?", a: "Netero" },
{ cat: "Anime", q: "Welcher Anime hat Notebook-Morde?", a: "Death Note" },
{ cat: "Anime", q: "Wie heißt der Titan mit Fell?", a: "Beast Titan" },
{ cat: "Anime", q: "Wer ist stärker: Naruto oder Sasuke laut Finale?", a: "Gleich stark/ähnlich" },
{ cat: "Anime", q: "Wie heißt die Kraft aus Jujutsu Kaisen?", a: "Cursed Energy" },
{ cat: "Anime", q: "Wie heißt der schwarze Drache in Dragon Ball GT?", a: "Shenlong/Omega Shenron" },

{ cat: "Filme", q: "Welcher Marvel-Film war der erste Avenger-Film?", a: "Iron Man" },
{ cat: "Filme", q: "Wie heißt der Clown aus Batman?", a: "Joker" },
{ cat: "Filme", q: "Welcher Film hat blaue Katzenmenschen?", a: "Avatar" },
{ cat: "Filme", q: "Wie heißt der Bruder von Thor?", a: "Loki" },
{ cat: "Filme", q: "Welcher Film hat den Satz 'Why so serious?'", a: "The Dark Knight" },
{ cat: "Filme", q: "Wie heißt der sprechende Waschbär bei Marvel?", a: "Rocket" },
{ cat: "Filme", q: "Wer schnipst Thanos weg?", a: "Iron Man/Tony Stark" },
{ cat: "Filme", q: "Welcher Film hat den Charakter Deadpool?", a: "Deadpool" },
{ cat: "Filme", q: "Wie heißt der Hammer von Thor?", a: "Mjölnir" },
{ cat: "Filme", q: "Welcher Film hat den Charakter John Wick?", a: "John Wick" },

{ cat: "Streamer", q: "Welche Farbe hat Twitchs Logo hauptsächlich?", a: "Lila" },
{ cat: "Streamer", q: "Wie nennt man Leute die nur zuschauen?", a: "Viewer" },
{ cat: "Streamer", q: "Was bedeutet 'Raid' auf Twitch?", a: "Zuschauer rüberschicken" },
{ cat: "Streamer", q: "Was ist ein Mod im Stream?", a: "Moderator" },
{ cat: "Streamer", q: "Was bedeutet 'Sub Goal'?", a: "Abo Ziel" },
{ cat: "Streamer", q: "Was bedeutet 'lurker'?", a: "Jemand der zuschaut ohne zu schreiben" },
{ cat: "Streamer", q: "Was bedeutet 'IRL Stream'?", a: "Real Life Stream" },
{ cat: "Streamer", q: "Welche Plattform nutzt oft Donations?", a: "Twitch/YouTube" },
{ cat: "Streamer", q: "Wie nennt man ein Gesicht vor der Kamera?", a: "Facecam" },
{ cat: "Streamer", q: "Was bedeutet 'Chat explodiert'?", a: "Sehr viele Nachrichten" },

{ cat: "Ragebait", q: "Ist Wasser nass?", a: "Diskussionsfrage" },
{ cat: "Ragebait", q: "Ist Müsli eine Suppe?", a: "Diskussionsfrage" },
{ cat: "Ragebait", q: "Was kommt zuerst: Milch oder Cornflakes?", a: "Diskussionsfrage" },
{ cat: "Ragebait", q: "Ist ein Hotdog ein Sandwich?", a: "Diskussionsfrage" },
{ cat: "Ragebait", q: "Ist Fortnite besser als Minecraft?", a: "Subjektiv" },
{ cat: "Ragebait", q: "Ist Ananas auf Pizza illegal?", a: "Diskussionsfrage" },
{ cat: "Ragebait", q: "Welche Farbe hat ein Spiegel?", a: "Leicht grünlich" },
{ cat: "Ragebait", q: "Zählt Strohhalm als Besteck?", a: "Nein" },
{ cat: "Ragebait", q: "Ist Cereal ein Getränk oder Essen?", a: "Essen" },
{ cat: "Ragebait", q: "Kann man Lasagne als Kuchen bezeichnen?", a: "Technisch diskutierbar" },

{ cat: "Schätzen", q: "Wie viele Haare hat ein Mensch ungefähr?", a: "ca. 100.000" },
{ cat: "Schätzen", q: "Wie viele Zuschauer hat Twitch gleichzeitig ungefähr?", a: "mehrere Millionen" },
{ cat: "Schätzen", q: "Wie viele Pokémon gibt es ungefähr?", a: "über 1000" },
{ cat: "Schätzen", q: "Wie viele Episoden hat One Piece ungefähr?", a: "über 1100" },
{ cat: "Schätzen", q: "Wie viele Knochen hat ein Baby ungefähr?", a: "ca. 300" },
{ cat: "Schätzen", q: "Wie viele Pixel hat Full HD?", a: "1920x1080" },
{ cat: "Schätzen", q: "Wie viele Sekunden hat ein Jahr ungefähr?", a: "31,5 Millionen" },
{ cat: "Schätzen", q: "Wie viele Liter Wasser trinkt ein Mensch pro Jahr ungefähr?", a: "ca. 700-1000 Liter" },
{ cat: "Schätzen", q: "Wie viele Atemzüge macht ein Mensch pro Tag ungefähr?", a: "ca. 20.000" },
{ cat: "Schätzen", q: "Wie viele Tasten hat eine normale Tastatur ungefähr?", a: "100-110" },

{ cat: "Memes", q: "Was bedeutet 'bro is flabbergasted'?", a: "Komplett überrascht" },
{ cat: "Memes", q: "Was bedeutet 'absolute cinema'?", a: "Peak Moment" },
{ cat: "Memes", q: "Was bedeutet 'standing on business'?", a: "Ernst machen" },
{ cat: "Memes", q: "Was bedeutet 'uncanny'?", a: "Unheimlich" },
{ cat: "Memes", q: "Was bedeutet 'gooner' Meme?", a: "Internet Brainrot Meme" },
{ cat: "Memes", q: "Was bedeutet 'nah this is wild'?", a: "Das ist verrückt" },
{ cat: "Memes", q: "Was bedeutet 'chat is this real'?", a: "Kann das wahr sein?" },
{ cat: "Memes", q: "Was bedeutet 'type shi'?", a: "So mäßig / genau sowas" },
{ cat: "Memes", q: "Was bedeutet 'locked in'?", a: "Voll fokussiert" },
{ cat: "Memes", q: "Was bedeutet 'crashout'?", a: "Komplett ausrasten" },
// ===== MEHR UNIQUE FRAGEN =====

{ cat: "Gaming", q: "Welches Spiel hat den Charakter Sage?", a: "Valorant" },
{ cat: "Gaming", q: "Wie heißt die seltenste Erzrüstung vor Netherite?", a: "Diamant" },
{ cat: "Gaming", q: "Welche Farbe hat ein Epic Item oft?", a: "Lila" },
{ cat: "Gaming", q: "Welches Spiel hat den Charakter Gibraltar?", a: "Apex Legends" },
{ cat: "Gaming", q: "Wie heißt die Firma hinter Steam?", a: "Valve" },
{ cat: "Gaming", q: "Welches Spiel hat den Charakter Leon Kennedy?", a: "Resident Evil" },
{ cat: "Gaming", q: "Wie heißt die stärkste Pistole oft in CS?", a: "Deagle" },
{ cat: "Gaming", q: "Welches Spiel hat den Operator Ghost?", a: "Call of Duty" },
{ cat: "Gaming", q: "Wie heißt die Welt in Mario?", a: "Pilzkönigreich" },
{ cat: "Gaming", q: "Welches Spiel hat die Champions League Autos?", a: "Rocket League" },

{ cat: "Anime", q: "Wie heißt Sasukes Bruder?", a: "Itachi" },
{ cat: "Anime", q: "Wie heißt der Sensei mit grüner Kleidung?", a: "Might Guy" },
{ cat: "Anime", q: "Welcher Anime hat Alchemie?", a: "Fullmetal Alchemist" },
{ cat: "Anime", q: "Wie heißt der Dämonenkönig in Seven Deadly Sins?", a: "Demon King" },
{ cat: "Anime", q: "Wie heißt die Kraft aus Dragon Ball?", a: "Ki" },
{ cat: "Anime", q: "Wer trainierte Gon?", a: "Biscuit/Bisky" },
{ cat: "Anime", q: "Wie heißt der Hund aus Chainsaw Man?", a: "Pochita" },
{ cat: "Anime", q: "Wie heißt die Stadt in Attack on Titan?", a: "Shiganshina" },
{ cat: "Anime", q: "Welcher Anime hat Shinigamis?", a: "Bleach" },
{ cat: "Anime", q: "Wie heißt der stärkste Fluch in JJK?", a: "Sukuna" },

{ cat: "Filme", q: "Wie heißt der blaue Genie aus Aladdin?", a: "Dschinni/Genie" },
{ cat: "Filme", q: "Wie heißt der Bösewicht aus Avengers Endgame?", a: "Thanos" },
{ cat: "Filme", q: "Welcher Film hat den Charakter Venom?", a: "Venom" },
{ cat: "Filme", q: "Wie heißt der Hauptcharakter aus Gladiator?", a: "Maximus" },
{ cat: "Filme", q: "Welcher Film hat den Satz 'Hakuna Matata'?", a: "König der Löwen" },
{ cat: "Filme", q: "Wie heißt der Roboter aus WALL-E?", a: "WALL-E" },
{ cat: "Filme", q: "Welcher Held benutzt Pfeil und Bogen?", a: "Hawkeye" },
{ cat: "Filme", q: "Wie heißt der König aus Wakanda?", a: "Black Panther/T'Challa" },
{ cat: "Filme", q: "Welcher Film hat Dinosaurier im Park?", a: "Jurassic Park" },
{ cat: "Filme", q: "Wie heißt der Tiger aus Kung Fu Panda?", a: "Tigress" },

{ cat: "Streamer", q: "Was bedeutet 'Prime Sub'?", a: "Kostenloses Twitch Abo mit Amazon Prime" },
{ cat: "Streamer", q: "Was bedeutet 'Backseat Gaming'?", a: "Von außen Tipps nervig geben" },
{ cat: "Streamer", q: "Was bedeutet 'Delay' im Stream?", a: "Verzögerung" },
{ cat: "Streamer", q: "Wie nennt man Zuschauer Rekord?", a: "Viewer Peak" },
{ cat: "Streamer", q: "Was bedeutet 'Emote only'?", a: "Nur Emotes im Chat" },
{ cat: "Streamer", q: "Was bedeutet 'clip farmen'?", a: "Absichtlich Clips erzeugen" },
{ cat: "Streamer", q: "Wie nennt man einen langen Stream?", a: "Subathon/Marathon" },
{ cat: "Streamer", q: "Was bedeutet 'react content'?", a: "Auf Videos reagieren" },
{ cat: "Streamer", q: "Was bedeutet 'face reveal'?", a: "Gesicht zeigen" },
{ cat: "Streamer", q: "Was bedeutet 'parasocial'?", a: "Zu persönliche Zuschauerbindung" },

{ cat: "Ragebait", q: "Ist Wasser Geschmackssache?", a: "Diskussionsfrage" },
{ cat: "Ragebait", q: "Sind Boneless Wings einfach Nuggets?", a: "Eigentlich ja" },
{ cat: "Ragebait", q: "Ist Die Hard ein Weihnachtsfilm?", a: "Diskussionsfrage" },
{ cat: "Ragebait", q: "Kann ein Stuhl ohne Rückenlehne noch Stuhl heißen?", a: "Diskussionsfrage" },
{ cat: "Ragebait", q: "Ist ein Korb voller Pommes ein Salat?", a: "Nein" },
{ cat: "Ragebait", q: "Ist ein Burrito technisch ein Wrap?", a: "Ja" },
{ cat: "Ragebait", q: "Sind Crocs Schuhe oder Verbrechen?", a: "Diskussionsfrage" },
{ cat: "Ragebait", q: "Ist Toastbrot Kuchen?", a: "Nein" },
{ cat: "Ragebait", q: "Kann man Wasser brennen?", a: "Nein" },
{ cat: "Ragebait", q: "Ist ein Hamburger ein Sandwich?", a: "Ja" },

{ cat: "Schätzen", q: "Wie viele FPS gelten als flüssig?", a: "60+" },
{ cat: "Schätzen", q: "Wie viele Gigabyte hat 1 Terabyte?", a: "1000/1024" },
{ cat: "Schätzen", q: "Wie viele Herzen hat ein Regenwurm?", a: "5" },
{ cat: "Schätzen", q: "Wie viele Liter passen in eine Badewanne ungefähr?", a: "ca. 150" },
{ cat: "Schätzen", q: "Wie viele Länder sind in Europa ungefähr?", a: "ca. 44" },
{ cat: "Schätzen", q: "Wie viele Kapitel hat One Piece ungefähr?", a: "über 1100" },
{ cat: "Schätzen", q: "Wie viele Bits sind ein Byte?", a: "8" },
{ cat: "Schätzen", q: "Wie viele Kalorien hat Wasser?", a: "0" },
{ cat: "Schätzen", q: "Wie viele Minuten hat ein Jahr ungefähr?", a: "525.600" },
{ cat: "Schätzen", q: "Wie viele Zuschauer passen ungefähr in ein Fußballstadion?", a: "20.000-100.000" },

{ cat: "Memes", q: "Was bedeutet 'NPC stream'?", a: "TikTok NPC Verhalten" },
{ cat: "Memes", q: "Was bedeutet 'fanum tax'?", a: "Essen klauen Meme" },
{ cat: "Memes", q: "Was bedeutet 'grimace shake'?", a: "McDonalds Meme" },
{ cat: "Memes", q: "Was bedeutet 'ohio meme'?", a: "Seltsame Dinge passieren" },
{ cat: "Memes", q: "Was bedeutet 'bomboclat' Meme?", a: "Jamaikanischer Ausdruck/Meme" },
{ cat: "Memes", q: "Was bedeutet 'gyatt damn'?", a: "Übertriebene Reaktion" },
{ cat: "Memes", q: "Was bedeutet 'chatting'?", a: "Einfach labern" },
{ cat: "Memes", q: "Was bedeutet 'bro spawned in'?", a: "Jemand taucht plötzlich auf" },
{ cat: "Memes", q: "Was bedeutet 'cuh'?", a: "Bro/Kumpel" },
{ cat: "Memes", q: "Was bedeutet 'uncle production'?", a: "Altmodisch produziert" },
// ===== NOCH MEHR FRAGEN =====

{ cat: "Gaming", q: "Welche Farbe hat ein Uncommon Item oft?", a: "Grün" },
{ cat: "Gaming", q: "Welches Spiel hat den Charakter Mercy?", a: "Overwatch" },
{ cat: "Gaming", q: "Wie heißt die stärkste Waffe in Halo oft?", a: "Energy Sword/Rocket Launcher" },
{ cat: "Gaming", q: "Welches Spiel hat den Charakter Octane?", a: "Apex Legends" },
{ cat: "Gaming", q: "Wie heißt die Firma hinter League of Legends?", a: "Riot Games" },
{ cat: "Gaming", q: "Welches Spiel hat die Map Mirage?", a: "Counter-Strike" },
{ cat: "Gaming", q: "Wie heißt der Modus mit 100 Spielern oft?", a: "Battle Royale" },
{ cat: "Gaming", q: "Welche Farbe haben Rare Items oft?", a: "Blau" },
{ cat: "Gaming", q: "Wie heißt das Monster aus Silent Hill?", a: "Pyramid Head" },
{ cat: "Gaming", q: "Welches Spiel hat den Charakter Tracer?", a: "Overwatch" },

{ cat: "Anime", q: "Wie heißt Narutos Sohn?", a: "Boruto" },
{ cat: "Anime", q: "Wie heißt Vegetas Sohn?", a: "Trunks" },
{ cat: "Anime", q: "Welcher Anime hat Soul Reapers?", a: "Bleach" },
{ cat: "Anime", q: "Wie heißt der stärkste Titan oft?", a: "Founding Titan" },
{ cat: "Anime", q: "Wie heißt das Dorf von Naruto?", a: "Konoha" },
{ cat: "Anime", q: "Wie heißt die Kraft aus One Piece?", a: "Teufelsfrüchte" },
{ cat: "Anime", q: "Wie heißt der Hauptcharakter aus Solo Leveling?", a: "Sung Jin-Woo" },
{ cat: "Anime", q: "Welcher Anime hat den Charakter Hisoka?", a: "Hunter x Hunter" },
{ cat: "Anime", q: "Wie heißt der Gott der Zerstörung?", a: "Beerus" },
{ cat: "Anime", q: "Wie heißt der Schwertkämpfer mit drei Schwertern?", a: "Zoro" },

{ cat: "Filme", q: "Wie heißt der blaue Alien Planet?", a: "Pandora" },
{ cat: "Filme", q: "Welcher Held kann mit Spinnenkräften Wände hochlaufen?", a: "Spider-Man" },
{ cat: "Filme", q: "Wie heißt der Hauptcharakter aus Deadpool?", a: "Wade Wilson" },
{ cat: "Filme", q: "Welcher Film hat den Charakter Groot?", a: "Guardians of the Galaxy" },
{ cat: "Filme", q: "Wie heißt der böse Zauberer aus Harry Potter?", a: "Voldemort" },
{ cat: "Filme", q: "Wie heißt der Löwe aus Narnia?", a: "Aslan" },
{ cat: "Filme", q: "Welcher Film hat den Charakter Buzz Lightyear?", a: "Toy Story" },
{ cat: "Filme", q: "Wie heißt der Roboter aus Transformers oft?", a: "Optimus Prime" },
{ cat: "Filme", q: "Welcher Film hat den Charakter Elsa?", a: "Frozen" },
{ cat: "Filme", q: "Wie heißt der Hauptcharakter aus Fluch der Karibik?", a: "Jack Sparrow" },

{ cat: "Streamer", q: "Was bedeutet 'chat interaction'?", a: "Mit Chat interagieren" },
{ cat: "Streamer", q: "Wie nennt man ein Gesichtsausdruck Bild im Chat?", a: "Emote" },
{ cat: "Streamer", q: "Was bedeutet 'AFK Screen'?", a: "Kurz weg Bildschirm" },
{ cat: "Streamer", q: "Was bedeutet 'BRB'?", a: "Be right back" },
{ cat: "Streamer", q: "Wie nennt man mehrere Monitore beim Streamen?", a: "Multi Monitor Setup" },
{ cat: "Streamer", q: "Was bedeutet 'green screen'?", a: "Hintergrund entfernen" },
{ cat: "Streamer", q: "Was bedeutet 'mod check'?", a: "Mods testen/ansprechen" },
{ cat: "Streamer", q: "Was bedeutet 'offline chat'?", a: "Chat obwohl Stream offline" },
{ cat: "Streamer", q: "Was ist ein Capture Card?", a: "Gerät zum Aufnehmen" },
{ cat: "Streamer", q: "Was bedeutet 'viewer games'?", a: "Mit Zuschauern spielen" },

{ cat: "Ragebait", q: "Ist ein Strohhalm ein Werkzeug?", a: "Diskussionsfrage" },
{ cat: "Ragebait", q: "Kann man Wasser kauen?", a: "Als Eis ja" },
{ cat: "Ragebait", q: "Ist ein Burrito technisch ein Sandwich?", a: "Diskussionsfrage" },
{ cat: "Ragebait", q: "Sind Socken Kleidung oder Accessoire?", a: "Kleidung" },
{ cat: "Ragebait", q: "Ist ein Chromebook ein echter PC?", a: "Diskussionsfrage" },
{ cat: "Ragebait", q: "Ist Cereal morgens Suppe?", a: "Diskussionsfrage" },
{ cat: "Ragebait", q: "Ist Lasagne ein Kuchen?", a: "Diskussionsfrage" },
{ cat: "Ragebait", q: "Sind Tomaten Gemüse?", a: "Botanisch Obst" },
{ cat: "Ragebait", q: "Ist Kaffee eine Suppe?", a: "Nein" },
{ cat: "Ragebait", q: "Ist ein Bonbon ein Snack?", a: "Ja" },

{ cat: "Schätzen", q: "Wie viele Pixel hat 4K ungefähr?", a: "3840x2160" },
{ cat: "Schätzen", q: "Wie viele Liter Wasser enthält ein Mensch ungefähr?", a: "ca. 60%" },
{ cat: "Schätzen", q: "Wie viele FPS schafft das Auge ungefähr?", a: "Keine feste Zahl" },
{ cat: "Schätzen", q: "Wie viele Kontinente gibt es?", a: "7" },
{ cat: "Schätzen", q: "Wie viele cm sind 1 Meter?", a: "100" },
{ cat: "Schätzen", q: "Wie viele mm sind 1 cm?", a: "10" },
{ cat: "Schätzen", q: "Wie viele Stunden hat ein Monat ungefähr?", a: "ca. 720" },
{ cat: "Schätzen", q: "Wie viele Tage hat ein Jahrzehnt ungefähr?", a: "3650" },
{ cat: "Schätzen", q: "Wie viele Folgen hat Naruto ohne Shippuden ungefähr?", a: "220" },
{ cat: "Schätzen", q: "Wie viele Tasten hat ein Klavier?", a: "88" },

{ cat: "Memes", q: "Was bedeutet 'bro got folded'?", a: "Komplett zerstört" },
{ cat: "Memes", q: "Was bedeutet 'nah that's crazy'?", a: "Das ist verrückt" },
{ cat: "Memes", q: "Was bedeutet 'internet brainrot'?", a: "Zu viel Internet Humor" },
{ cat: "Memes", q: "Was bedeutet 'cooked beyond belief'?", a: "Komplett verloren" },
{ cat: "Memes", q: "Was bedeutet 'unc got no aura'?", a: "Peinliche Ausstrahlung" },
{ cat: "Memes", q: "Was bedeutet 'he got motion'?", a: "Er hat Erfolg/Aufmerksamkeit" },
{ cat: "Memes", q: "Was bedeutet 'goofy'?", a: "Lustig/dumm" },
{ cat: "Memes", q: "Was bedeutet 'aura loss'?", a: "Coolness verloren" },
{ cat: "Memes", q: "Was bedeutet 'bro is NOT him'?", a: "Er ist nicht krass" },
{ cat: "Memes", q: "Was bedeutet 'cooked chat'?", a: "Chat ist verloren" },
// ===== EXTRA 270 FRAGEN START =====

{ cat: "Gaming", q: "Welches Spiel hat den Charakter Wraith?", a: "Apex Legends" },
{ cat: "Gaming", q: "Wie heißt die seltenste Spitzhacke in Fortnite laut Community oft?", a: "Renegade Raider Pickaxe/seltene Event Picks" },
{ cat: "Gaming", q: "Welches Spiel hat den Charakter Sombra?", a: "Overwatch" },
{ cat: "Gaming", q: "Wie heißt die Firma hinter GTA?", a: "Rockstar Games" },
{ cat: "Gaming", q: "Welches Spiel hat Creeper Explosionen?", a: "Minecraft" },
{ cat: "Gaming", q: "Wie heißt die stärkste CS Pistole oft?", a: "Desert Eagle" },
{ cat: "Gaming", q: "Welches Spiel hat den Charakter Lifeline?", a: "Apex Legends" },
{ cat: "Gaming", q: "Wie heißt die seltenste Pokémon Karte oft?", a: "Pikachu Illustrator" },
{ cat: "Gaming", q: "Welches Spiel hat den Charakter Phoenix?", a: "Valorant" },
{ cat: "Gaming", q: "Wie heißt die Firma hinter Valorant?", a: "Riot Games" },

{ cat: "Gaming", q: "Welches Spiel hat den Charakter Mei?", a: "Overwatch" },
{ cat: "Gaming", q: "Wie heißt das beliebte Survival-Spiel mit Würfeln?", a: "Minecraft" },
{ cat: "Gaming", q: "Welches Spiel hat den Charakter Mirage?", a: "Apex Legends" },
{ cat: "Gaming", q: "Wie heißt die Währung in Fortnite?", a: "V-Bucks" },
{ cat: "Gaming", q: "Welches Spiel hat den Charakter Reyna?", a: "Valorant" },
{ cat: "Gaming", q: "Wie heißt das Auto-Spiel mit Boost?", a: "Rocket League" },
{ cat: "Gaming", q: "Welches Spiel hat den Charakter Genji?", a: "Overwatch" },
{ cat: "Gaming", q: "Wie heißt der Zombie Modus in COD?", a: "Zombies" },
{ cat: "Gaming", q: "Welches Spiel hat den Charakter Killjoy?", a: "Valorant" },
{ cat: "Gaming", q: "Wie heißt die stärkste Spitzhacke in Minecraft?", a: "Netherite Spitzhacke" },

{ cat: "Anime", q: "Wie heißt der Hokage vor Naruto?", a: "Kakashi" },
{ cat: "Anime", q: "Welcher Anime hat Teufelsfrüchte?", a: "One Piece" },
{ cat: "Anime", q: "Wie heißt der stärkste Uchiha oft?", a: "Madara" },
{ cat: "Anime", q: "Welcher Anime hat den Charakter L?", a: "Death Note" },
{ cat: "Anime", q: "Wie heißt der Lehrer von Yuji Itadori?", a: "Gojo" },
{ cat: "Anime", q: "Welcher Anime hat die Akatsuki?", a: "Naruto" },
{ cat: "Anime", q: "Wie heißt der Titan mit Rüstung?", a: "Armored Titan" },
{ cat: "Anime", q: "Welcher Anime hat den Charakter Hisoka?", a: "Hunter x Hunter" },
{ cat: "Anime", q: "Wie heißt der Bruder von Tanjiro?", a: "Er hat keinen Bruder" },
{ cat: "Anime", q: "Welcher Anime hat den Charakter Sukuna?", a: "Jujutsu Kaisen" },

{ cat: "Anime", q: "Wie heißt Narutos stärkste Form oft?", a: "Baryon Mode" },
{ cat: "Anime", q: "Welcher Anime hat Shinigamis?", a: "Bleach" },
{ cat: "Anime", q: "Wie heißt der Dämon aus Chainsaw Man?", a: "Pochita" },
{ cat: "Anime", q: "Welcher Anime hat den Charakter Levi?", a: "Attack on Titan" },
{ cat: "Anime", q: "Wie heißt Gons bester Freund?", a: "Killua" },
{ cat: "Anime", q: "Welcher Anime hat den Charakter Madara?", a: "Naruto" },
{ cat: "Anime", q: "Wie heißt die Energie in Dragon Ball?", a: "Ki" },
{ cat: "Anime", q: "Welcher Anime hat den Charakter Aizen?", a: "Bleach" },
{ cat: "Anime", q: "Wie heißt Ruffys Bruder?", a: "Ace/Sabo" },
{ cat: "Anime", q: "Welcher Anime hat den Charakter Johan Liebert?", a: "Monster" },

{ cat: "Filme", q: "Wie heißt der Vater von Simba?", a: "Mufasa" },
{ cat: "Filme", q: "Welcher Film hat den Charakter Neo?", a: "Matrix" },
{ cat: "Filme", q: "Wie heißt der Hammer von Thor?", a: "Mjölnir" },
{ cat: "Filme", q: "Welcher Film hat den Charakter Groot?", a: "Guardians of the Galaxy" },
{ cat: "Filme", q: "Wie heißt der Hauptcharakter aus Joker?", a: "Arthur Fleck" },
{ cat: "Filme", q: "Welcher Film hat den Charakter Olaf?", a: "Frozen" },
{ cat: "Filme", q: "Wie heißt der grüne Oger?", a: "Shrek" },
{ cat: "Filme", q: "Welcher Film hat den Charakter Buzz?", a: "Toy Story" },
{ cat: "Filme", q: "Wie heißt der Butler von Batman?", a: "Alfred" },
{ cat: "Filme", q: "Welcher Film hat den Charakter Pennywise?", a: "Es" },

{ cat: "Filme", q: "Wie heißt Iron Mans KI?", a: "Jarvis" },
{ cat: "Filme", q: "Welcher Film hat den Charakter Dobby?", a: "Harry Potter" },
{ cat: "Filme", q: "Wie heißt der blaue Alien Planet?", a: "Pandora" },
{ cat: "Filme", q: "Welcher Film hat den Charakter Venom?", a: "Venom" },
{ cat: "Filme", q: "Wie heißt der König von Wakanda?", a: "T'Challa" },
{ cat: "Filme", q: "Welcher Film hat den Charakter Sid?", a: "Ice Age" },
{ cat: "Filme", q: "Wie heißt der Tiger aus Kung Fu Panda?", a: "Tigress" },
{ cat: "Filme", q: "Welcher Film hat den Charakter Gru?", a: "Ich – Einfach unverbesserlich" },
{ cat: "Filme", q: "Wie heißt der Hauptcharakter aus John Wick?", a: "John Wick" },
{ cat: "Filme", q: "Welcher Film hat den Charakter Aslan?", a: "Narnia" },

{ cat: "Streamer", q: "Was bedeutet 'chat hopping'?", a: "Zwischen Chats wechseln" },
{ cat: "Streamer", q: "Was bedeutet 'mic muted'?", a: "Mikro stumm" },
{ cat: "Streamer", q: "Wie nennt man kleine Bilder im Twitch Chat?", a: "Emotes" },
{ cat: "Streamer", q: "Was bedeutet 'sub only mode'?", a: "Nur Abonnenten schreiben" },
{ cat: "Streamer", q: "Wie nennt man die Stream Vorschau?", a: "Thumbnail" },
{ cat: "Streamer", q: "Was bedeutet 'stream sniper'?", a: "Jemand verfolgt den Stream ingame" },
{ cat: "Streamer", q: "Was bedeutet 'cam off'?", a: "Kamera aus" },
{ cat: "Streamer", q: "Wie nennt man das Ende eines Streams?", a: "Outro/Offline" },
{ cat: "Streamer", q: "Was bedeutet 'viewer count'?", a: "Zuschauerzahl" },
{ cat: "Streamer", q: "Wie nennt man ein kurzes lustiges Streamvideo?", a: "Clip" },

{ cat: "Streamer", q: "Was bedeutet 'hosten' auf Twitch früher?", a: "Anderen Stream zeigen" },
{ cat: "Streamer", q: "Was bedeutet 'facecam'?", a: "Kamera vom Gesicht" },
{ cat: "Streamer", q: "Wie nennt man Musik ohne DMCA?", a: "DMCA-Free Music" },
{ cat: "Streamer", q: "Was bedeutet 'stream overlay'?", a: "Grafiken im Stream" },
{ cat: "Streamer", q: "Wie nennt man den Stream Titel?", a: "Title" },
{ cat: "Streamer", q: "Was bedeutet 'stream lag'?", a: "Verzögerter Stream" },
{ cat: "Streamer", q: "Wie nennt man mehrere Kameras im Stream?", a: "Multi Cam" },
{ cat: "Streamer", q: "Was bedeutet 'chat delay'?", a: "Verzögerter Chat" },
{ cat: "Streamer", q: "Wie nennt man eine Spendennachricht?", a: "Donation Alert" },
{ cat: "Streamer", q: "Was bedeutet 'stream deck'?", a: "Button Steuerung fürs Streaming" },

{ cat: "Ragebait", q: "Ist Wasser im Wasser nass?", a: "Diskussionsfrage" },
{ cat: "Ragebait", q: "Ist ein Taco ein Sandwich?", a: "Diskussionsfrage" },
{ cat: "Ragebait", q: "Sind Ravioli kleine Lasagnen?", a: "Diskussionsfrage" },
{ cat: "Ragebait", q: "Ist Cola besser warm oder kalt?", a: "Kalt laut Mehrheit" },
{ cat: "Ragebait", q: "Ist ein Stuhl mit Rollen noch Stuhl?", a: "Ja" },
{ cat: "Ragebait", q: "Ist ein Burger ohne Brot noch Burger?", a: "Diskussionsfrage" },
{ cat: "Ragebait", q: "Ist Wasser mit Geschmack noch Wasser?", a: "Ja" },
{ cat: "Ragebait", q: "Ist ein Döner ein Sandwich?", a: "Technisch ja" },
{ cat: "Ragebait", q: "Ist ein Smoothie Essen oder Getränk?", a: "Beides möglich" },
{ cat: "Ragebait", q: "Sind Chicken Nuggets Hähnchen oder Formmasse?", a: "Beides" },

{ cat: "Ragebait", q: "Ist Anime Cartoon?", a: "Technisch ja" },
{ cat: "Ragebait", q: "Ist Ketchup ein Smoothie?", a: "Nein" },
{ cat: "Ragebait", q: "Ist Müsli roh?", a: "Ja" },
{ cat: "Ragebait", q: "Ist ein Wrap ein Burrito?", a: "Ähnlich" },
{ cat: "Ragebait", q: "Ist Lasagne Pasta oder Kuchen?", a: "Pasta" },
{ cat: "Ragebait", q: "Sind Socken Schuhe?", a: "Nein" },
{ cat: "Ragebait", q: "Ist Suppe ein Getränk?", a: "Diskussionsfrage" },
{ cat: "Ragebait", q: "Ist ein Eiswürfel trocken?", a: "Außen nein" },
{ cat: "Ragebait", q: "Ist TikTok Unterhaltung oder Gehirnschaden?", a: "Diskussionsfrage" },
{ cat: "Ragebait", q: "Ist ein Strohhalm Pasta?", a: "Nein" },
];